spring:
  profiles:
    active: test
---
spring:
  profiles: test
  application:
    name: lanhuigu-config-client-test
server:
  port: 9005
---
spring:
  profiles: prod
  application:
    name: lanhuigu-config-client-prod
server:
  port: 8881